### ISSUE TITLE
在Kotlin中使用，Boolean出错

### ISSUE THREAD

**Issue by imyyq-star** [simplezhli/Saber#4]
报错信息：

`e: [kapt] An exception occurred: java.lang.IllegalArgumentException: invalid type parameter: boolean
	at com.squareup.javapoet.Util.checkArgument(Util.java:53)
	at com.squareup.javapoet.ParameterizedTypeName.<init>(ParameterizedTypeName.java:51)
	at com.squareup.javapoet.ParameterizedTypeName.<init>(ParameterizedTypeName.java:38)
	at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:114)
	at com.zl.weilu.saber.compiler.BindViewModelProcessor.brewActivity(BindViewModelProcessor.java:167)
	at com.zl.weilu.saber.compiler.BindViewModelProcessor.process(BindViewModelProcessor.java:43)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:132)`

绑定如下：

@OnChange
fun onChange(isFinishOrFailed: Boolean)

**Comment by simplezhli** [comment]
基础类型确实使用‘javapoet’支持的不够友好，我下面会使用'kotlinpoet'去适配这块。感谢反馈！

**Comment by simplezhli** [comment]
@imyyq-star 我暂时适配了一下kotlin基础类型，升级至0.2.5尝试一下。记得Boolean后加?：`fun onChange(isFinishOrFailed: Boolean?)`
